base_model = "moonshotai/kimi-k2.5"
attachment = true
temperature = true
reasoning_options = []

[interleaved]
field = "reasoning_details"

[cost]
input = 0.4
output = 1.9
cache_read = 0.09

[modalities]
input = ["text", "image"]
